### ISSUE TITLE
Can Windows also be supported?

### ISSUE THREAD

**Issue by 0Franky** [yosemiteyss/flutter_volume_controller#11]
Hi @yosemiteyss,
first of all thank you for your contribution!

I wanted to ask as the title suggests, if it is possible to add compatibility for windows as well.

Thanks in advance and have a nice day!

**Comment by yosemiteyss** [comment]
Hi, thanks for supporting the package. I will do some research on that once I'm free.

**Comment by 0Franky** [comment]
Thank you!

**Comment by yosemiteyss** [comment]
Hi @0Franky , I have added windows support in 1.1.0. I will close this issue for now. :)

**Comment by 0Franky** [comment]
Thank you so much!
