### ISSUE TITLE
Can Linux also be supported?

### ISSUE THREAD

**Issue by 0Franky** [yosemiteyss/flutter_volume_controller#16]
Hi @yosemiteyss,
thanks again for your work on Windows!

I want to ask you if it is possible to add compatibility for linux too.

Thanks in advance and have a nice day!

**Comment by yosemiteyss** [comment]
Hi, I will look into it once I'm free.

**Comment by yosemiteyss** [comment]
Hi, I has added Linux support in version 1.2.0. This issue can be closed.
