### ISSUE TITLE
setVolume sets the wrong value that is passed

### ISSUE THREAD

**Issue by tenraneko** [yosemiteyss/flutter_volume_controller#25]
Hello! I can't set the volume I want. I need it to be accurate, it's very important, but neither setVolume nor lowerVolume sets values like 0.1 or 0.2 etc. the value is always long and wrong.
Even if I manually set the volume to exactly 100%, to the end, then any method makes the volume not correct.

`await FlutterVolumeController.setVolume(0.1);`
`print(await FlutterVolumeController.getVolume()); // Result is 0.09803921729326248`

`await FlutterVolumeController.setVolume(0.2);`
`print(await FlutterVolumeController.getVolume()); // Result is 0.19607843458652496`

**Comment by yosemiteyss** [comment]
Hi, may I ask in what platform you face this issue?

**Comment by tenraneko** [comment]
> Hi, may I ask in what platform you face this issue?

Oh sorry.
Platform - Windows (tested only on win 11)

**Comment by tenraneko** [comment]
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22000.1281], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by tenraneko** [comment]
in 1.2.1+1 issue is fixed. Thank you 😊

**Comment by yosemiteyss** [comment]
I still find some issues on volume floating point precision, I will fix them on upcoming releases.

**Comment by tenraneko** [comment]
> I still find some issues on volume floating point precision, I will fix them on upcoming releases.

Yes, I saw there is a small error, but it is no longer critical (at least for me). Of course, if you can fix it and make it 100% accurate, then I will be glad. Thank you very much
