### ISSUE TITLE
[Feature] Listening to volume changes without changing the volume

### ISSUE THREAD

**Issue by lollipopkit** [yosemiteyss/flutter_volume_controller#54]
For example: listen to the volume keys to **change the font size**, **page up and down**.

Is there any way to do this?

Thanks.

**Comment by yosemiteyss** [comment]
Detect volume button presses is not possible on iOS as there is no official API. You may try some hacky ways like resetting volume to previous level right after volume changes, to mimic the button press event. But beware that your app might get rejected when submitting to app store.

In Android, you can use the following package to intercept volume key presses: 
https://pub.dev/packages/flutter_android_volume_keydown
Notes that it overrides the `onKeyDown` method from activity, and you have to edit the native codes.

**Comment by lollipopkit** [comment]
Thanks for your reply :)
