### ISSUE TITLE
FlutterVolumeController.showSystemUI

### ISSUE THREAD

**Issue by CalsRanna** [yosemiteyss/flutter_volume_controller#58]
Seems `FlutterVolumeController.showSystemUI ` does not work in android.
Or may I call this in the main.dart?

**Comment by CalsRanna** [comment]
Is there a way to disable dialog of system volume while press physical volume button?

**Comment by yosemiteyss** [comment]
`FlutterVolumeController.showSystemUI` only works when using `setVolume` function. Currently there is no intuitive way to disable system UI when pressing volume button, unless we override `Activity::onKeyDown` event and implement custom controls.

**Comment by CalsRanna** [comment]
Thx for that. I use fork from flutter_android_volume_keydown and do my work.
