### ISSUE TITLE
Setting audio stream voice call in video call only works for setVolume

### ISSUE THREAD

**Issue by janhelwich** [yosemiteyss/flutter_volume_controller#66]
**Describe the bug**
When I am in a video call and set teh audio manager like this FlutterVolumeController.setAndroidAudioStream(stream: AudioStream.voiceCall) it is still using another AudioStream. When I call FlutterVolumeController.getAndroidAudioStream() the correct voiceCall Stream is returned though.

It works to set the volume via  FlutterVolumeController.setVolume(vol, stream: _currAudioStream) with the required stream.

**Plugin version**
1.3.0

**Platform:**
 - OS: Android 12
 - Device: Samsung Tab A7

**Comment by yosemiteyss** [comment]
I am not quite understand the question. Is the video call handled by your app or other third party app? It would be better if you can provide code sample to reproduce the issue.

**Comment by janhelwich** [comment]
The video call is handled by my app. What I assumed was that if I set the AudioStream once in the FlutterVolumeController it would be set for good. Not sure what the WebRTC plugin does "under the hood" so this implementation works just fine for me:

`import 'package:flutter/material.dart';
import 'package:flutter_volume_controller/flutter_volume_controller.dart';
import 'package:telemarie/constants.dart';


abstract class AndroidVolumeControl {
  double maxVol = 1, currentVol = 1;
  Color mainColor = Colors.white;
  Color fontColor = Colors.black;
  bool _isInitialized = false;
  AudioStream _currAudioStream = AudioStream.system;

  void _initAndroidVolumeCtrl({forWhiteBackground = false}) {
    FlutterVolumeController.updateShowSystemUI(false);
    if (forWhiteBackground) {
      mainColor = Color(COLOR_PRIMARY);
      fontColor = Colors.white;
    } else {
      mainColor = Colors.white;
      fontColor = Colors.black;
    }
    _initVolumes();
  }

  void initAndroidVolumeCtrlForMusicStream() {
    _currAudioStream = AudioStream.music;
    FlutterVolumeController.setAndroidAudioStream(stream: AudioStream.music);
    _initAndroidVolumeCtrl();
  }

  initAndroidVolumeCtrlForRinging() {
    _currAudioStream = AudioStream.ring;
    FlutterVolumeController.setAndroidAudioStream(stream: AudioStream.ring);
    _initAndroidVolumeCtrl();
  }

  initAndroidVolumeCtrlForCall() {
    _currAudioStream = AudioStream.voiceCall;
    FlutterVolumeController.setAndroidAudioStream(stream: AudioStream.voiceCall);
    _initVolumes();
  }

  _initVolumes() async {
    await _setCurrentVol();
    setState(() {
      _isInitialized= true;
    });
  }

  Future<void> _setCurrentVol() async {
    currentVol = ((await FlutterVolumeController.getVolume(stream: _currAudioStream))! * maxVol);
    print("currentVol: $currentVol");
  }

  updateVolumes() async {
    await _setCurrentVol();
    setState(() {});
  }

  void setState(VoidCallback fn);

  setVol(double i) async {
    try{
      await FlutterVolumeController.setVolume(i/maxVol, stream: _currAudioStream);
    } catch(e){
      print(e);
    }
  }

  increaseVolume() {
    FlutterVolumeController.raiseVolume(null,stream: _currAudioStream);
    updateVolumes();
  }

  decreaseVolume() {
    FlutterVolumeController.lowerVolume(null,stream: _currAudioStream);
    updateVolumes();
  }

  Positioned volumeCtrl(BuildContext context, {double right = 20}) {
    return Positioned(
      top: MediaQuery.of(context).size.height * 0.2,
      right: right,
      child: Align(
          alignment: Alignment.topRight,
          child: Column(
            children: [
              FloatingActionButton(
                backgroundColor: mainColor,
                foregroundColor: fontColor,
                heroTag: 'speakerFAB',
                child: Icon(
                  Icons.volume_up_rounded,
                  size: 42,
                ),
                onPressed: increaseVolume,
              ),
              Padding(
                padding: EdgeInsets.only(top: 7, bottom: 7),
                child: RotatedBox(
                  quarterTurns: 3,
                  child: SliderTheme(
                    data: SliderThemeData(
                      trackHeight: 20,
                      inactiveTrackColor: Colors.white60,
                      activeTrackColor: mainColor,
                      thumbShape: RoundSliderThumbShape(
                          enabledThumbRadius: 20.0),
                      thumbColor: mainColor,
                    ),
                    child: Slider(
                      value: currentVol,
                      max: maxVol,
                      min: 0,
                      onChanged: (double d) {
                        if(_isInitialized){
                          setVol(d);
                          updateVolumes();
                        }
                      },
                    ),
                  ),
                ),
              ),
              FloatingActionButton(
                backgroundColor: mainColor,
                foregroundColor: fontColor,
                heroTag: 'speakerFAB',
                child: Icon(
                  Icons.volume_down_rounded,
                  size: 42,
                ),
                onPressed: decreaseVolume,
              ),
            ],
          )),
    );
  }

}
`

**Comment by yosemiteyss** [comment]
Typically `FlutterVolumeController.setAndroidAudioStream` is set once during `initState()`. But if some other library overrides the stream settings, you may need to recall `setAndroidAudioStream()` again before `setVolume()`, as `setVolume()` only updates the volume level, but not activating the audio stream for you.

**Comment by yosemiteyss** [comment]
Closed as above.
