### ISSUE TITLE
Increase volume with step size (.2) jumps from .4 to .8

### ISSUE THREAD

**Issue by janhelwich** [yosemiteyss/flutter_volume_controller#67]
**Describe the bug**
When I am in a video call and increase the volume with FlutterVolumeController.raiseVolume(.2,stream: _currAudioStream) the volume jumps from .4 to .8. When I user FlutterVolumeController.raiseVolume(null,stream: _currAudioStream) it works as expected.

**Plugin version**
1.3.0

**Platform:**
 - OS: Android 12
 - Device: Samsung Tab A7

**Comment by yosemiteyss** [comment]
Some devices or audio streams may have fewer numbers of volume steps (default is 15). Using fixed volume stepping value may produce a rounded off result. In this case, I suggest to keep using ` FlutterVolumeController.raiseVolume(null,stream: _currAudioStream)` as it's the default system behavior.

**Comment by yosemiteyss** [comment]
Closed as it's expected behavior.
