### ISSUE TITLE
is it possible to read the "Dialing Keypad" setting #21

### ISSUE THREAD

**Issue by marcodecarolisidt** [yosemiteyss/flutter_volume_controller#71]
**Describe the bug**

Can we read this volume's setting for android? 
<img width="222" alt="image" src="https://github.com/yosemiteyss/flutter_volume_controller/assets/75722932/8a72444d-a8e6-49d7-8aee-5d8b3f2e4764">

**Comment by yosemiteyss** [comment]
To get system volume, use `FlutterVolumeController.getVolume(stream: AudioStream.system)`.

**Comment by marcodecarolisidt** [comment]
But is it possible to know if "Dialing Keypad" is on or off?

**Comment by yosemiteyss** [comment]
Seems impossible. Adjust dial pad tones settings requires `android.permission.WRITE_SETTINGS`, which can only be granted by system app.
