### ISSUE TITLE
how to listen to ios ringer mode changed 

### ISSUE THREAD

**Issue by heshesh2010** [yosemiteyss/flutter_volume_controller#72]
Hi , i want to ask how to listen when ringer button is pressed so now it will be muted or not

**Comment by yosemiteyss** [comment]
Hi, there is no API in iOS to detect the ring/silent button switching event.

**Comment by heshesh2010** [comment]
So how instagram native app uses ios api to detect when u switch ringer
button off / on

**Comment by yosemiteyss** [comment]
I'm not sure which part of instagram uses ringer mode detection. Could you provide more details?

**Comment by yosemiteyss** [comment]
I guessed it's managed by `AVAudioSession`. You can try using `FlutterVolumeController.setIOSAudioSessionCategory` to see if it can achieve the same result.

**Comment by heshesh2010** [comment]
> I guessed it's managed by `AVAudioSession`. You can try using `FlutterVolumeController.setIOSAudioSessionCategory` to see if it can achieve the same result.

thank u it works
