### ISSUE TITLE
Error while using package!

### ISSUE THREAD

**Issue by tushar11kh** [yosemiteyss/flutter_volume_controller#74]
Hey @yosemiteyss I am working on a repo which uses flutter_volume_controller package. I tried many things but I am not able to make it work.

<img width="840" alt="Screenshot 2024-01-28 at 2 18 57 PM" src="https://github.com/yosemiteyss/flutter_volume_controller/assets/144731286/fe29f21b-197b-4c3e-866f-570fa93957ba">

can you please help me in this...

**Comment by yosemiteyss** [comment]
Have you tried running `flutter clean` and remove the package in `.pub-cache` folder?

**Comment by tushar11kh** [comment]
> Have you tried running `flutter clean` and remove the package in `.pub-cache` folder?

try 1) I tried what you told me it didn't work either....

try 2) I have download this package manually from https://pub.dev/packages/flutter_volume_controller/versions and used flutter pub get for the same and then pasted it in  .pub-cache/hosted/pub.dev
It also didn't work

**Comment by yosemiteyss** [comment]
Whats your flutter sdk version?

**Comment by tushar11kh** [comment]
> Whats your flutter sdk version?
hey now its working I have copied and pasted

  flutter_plugin_android_lifecycle: ^2.0.17
  
  and 
  
    plugin:
    platforms:
      android:
        package: com.yosemiteyss.flutter_volume_controller
        pluginClass: FlutterVolumeControllerPlugin
      ios:
        pluginClass: FlutterVolumeControllerPlugin
      macos:
        pluginClass: FlutterVolumeControllerPlugin
      windows:
        pluginClass: FlutterVolumeControllerPluginCApi
      linux:
        pluginClass: FlutterVolumeControllerPlugin
  
  in pubspec.yaml of project i am working on and restarted my machine and now its working...
  
  I am using Flutter 3.19.0-9.0.pre
